import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import ToasterProvider from "@/providers/toast-provider";
import QueryProvider from "@/components/QueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import ProgressBarProvider from "@/components/ProgressBarProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "JNeedle-Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`relative min-h-screen antialiased`, roboto.className)}
      >
        <ProgressBarProvider>
          <QueryProvider>
            <ToasterProvider />
            {children}
            <ReactQueryDevtools />
          </QueryProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
